# Generated by Django 3.1.4 on 2021-01-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.CharField(blank=True, choices=[('project_ksw_youjibosu', '감사원 - 유지보수'), ('project_ksw_siljuck', '감사원 - 실적평가'), ('project_ykb_youjibosu', '외교부 - 전자감사'), ('default', '프로젝트를 선택해주세요')], max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, max_length=200, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('work_class', models.CharField(max_length=50, null=True)),
                ('work_class_detail', models.CharField(max_length=50, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
