# Generated by Django 3.1.4 on 2021-01-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_remove_request_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='mail',
        ),
        migrations.AddField(
            model_name='request',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='work_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='work_class_detail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
